workflows:
  android-apk:
    name: Android APK (Expo prebuild)
    max_build_duration: 60
    environment:
      vars:
        NODE_VERSION: 20
        CI: 1
        EXPO_NO_TELEMETRY: 1
        EXPO_DEBUG: 1
      node: 20
      java: 17
      xcode: 15.1
    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper
        - $CM_BUILD_DIR/frontend/node_modules
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: ".*"
          include: true
          source: true
    scripts:
      - name: Show environment
        script: |
          node -v
          npm -v || true
          yarn -v || true
          java -version
          echo "Working dir: $CM_BUILD_DIR"
          ls -la
          echo "Frontend dir contents:" && ls -la frontend
      - name: Clean caches (Metro & Gradle)
        script: |
          cd frontend
          rm -rf .metro-cache || true
          rm -rf node_modules/.cache || true
          cd android
          ./gradlew clean --no-daemon || true
      - name: Install dependencies (force expo if missing)
        script: |
          cd frontend
          corepack enable || true
          rm -f package-lock.json
          if [ -f yarn.lock ]; then
            yarn install --non-interactive --frozen-lockfile || yarn install --non-interactive
          else
            npm ci || npm i
          fi
          # Force install critical deps if resolver doesn't find them
          node -e "require.resolve('expo/package.json')" 2>/dev/null || yarn add expo@~53.0.22 --exact
          node -e "require.resolve('expo-router/package.json')" 2>/dev/null || yarn add expo-router@~5.1.6 --exact
          node -e "require.resolve('react-native/package.json')" 2>/dev/null || yarn add react-native@0.79.5 --exact
          node -e "require.resolve('react-native-reanimated/package.json')" 2>/dev/null || yarn add react-native-reanimated@~3.17.4 --exact
          # Re-run install to ensure lockfile consistency and peer deps
          yarn install --non-interactive --frozen-lockfile || true
          # Verify
          node -e "console.log('expo=', require('expo/package.json').version); console.log('router=', require('expo-router/package.json').version)"
          test -f babel.config.js || (echo "Missing frontend/babel.config.js" && exit 1)
          # Fix: remove deprecated expo-router/babel plugin if present
          node -e "const fs=require('fs'); const p='babel.config.js'; let t=fs.readFileSync(p,'utf8'); if(t.includes('expo-router/babel')){ t=t.replace(/\s*require\.resolve\('expo-router\/babel'\),?/,''); t=t.replace(/['\"]expo-router\/babel['\"],?/,''); fs.writeFileSync(p,t); console.log('Removed expo-router/babel plugin'); } else { console.log('No expo-router/babel plugin to remove'); }"
      - name: Expo prebuild (Android)
        script: |
          export CI=1
          cd frontend
          npx --yes expo@latest prebuild --platform android --clean
      - name: Pre-bundle JS (debug to surface Metro errors)
        script: |
          set -e
          cd frontend
          mkdir -p android/app/build/generated/assets/createBundleReleaseJsAndAssets
          mkdir -p android/app/build/generated/res/createBundleReleaseJsAndAssets
          mkdir -p android/app/build/intermediates/sourcemaps/react/release
          npx --yes expo@latest export:embed \
            --platform android \
            --dev false \
            --reset-cache \
            --entry-file node_modules/expo-router/entry.js \
            --bundle-output android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle \
            --assets-dest android/app/build/generated/res/createBundleReleaseJsAndAssets \
            --sourcemap-output android/app/build/intermediates/sourcemaps/react/release/index.android.bundle.packager.map \
            --minify false \
            --verbose
      - name: Build APK (with logs)
        script: |
          set -o pipefail
          cd frontend/android
          ./gradlew assembleRelease --no-daemon --stacktrace --info --warning-mode all | tee gradle-build.log
          echo "Problems report (if any):"
          if [ -f build/reports/problems/problems-report.html ]; then
            ls -la build/reports/problems
            echo "---- Extracting errors from problems-report.html ----"
            sed -n '1,200p' build/reports/problems/problems-report.html | sed -n '1,200p'
          fi
          echo "---- Tail gradle-build.log ----"
          tail -n 200 gradle-build.log || true
    artifacts:
      - frontend/android/app/build/outputs/apk/release/*.apk
      - frontend/android/gradle-build.log
      - frontend/android/build/reports/problems/problems-report.html
    publishing:
      email:
        recipients:
          - thomas1290@gmx.net
        notify:
          success: true
          failure: true